Repository THE-SOPT-Joint-Seminar-Danggn/Daangn-iOS, pull requests merged in 2022-06, with the labels that each got.

#12 [Feat] ListItem과 ItemDetail 화면 전환 연결
  Danggn.xcodeproj/project.pbxproj
  Danggn/Resource/Assets.xcassets/ItemImages/no_image.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ItemImages/no_image.imageset/no_image 1.png
  Danggn/Resource/Assets.xcassets/ItemImages/no_image.imageset/no_image 1@2x.png
  Danggn/Resource/Assets.xcassets/ItemImages/no_image.imageset/no_image 1@3x.png
  Danggn/Screen/Home/Controller/ListItemViewController.swift
  Danggn/Screen/Home/View/ListItem.storyboard
  Danggn/Service/FeedService.swift
Labels: 담인🥕, Feat

#11 [Feat] 상품 상세 페이지 조회 서버 연결
  Danggn.xcodeproj/project.pbxproj
  Danggn/DataModel/BaseResponse.swift
  Danggn/DataModel/FeedDetailModel.swift
  Danggn/Network/APIConstants.swift
  Danggn/Screen/Home/Cell/PostDetailTableViewCell.swift
  Danggn/Screen/Home/Cell/PostImageCollectionCell.swift
  Danggn/Screen/Home/Cell/PostImageTableViewCell.swift
  Danggn/Screen/Home/Controller/ItemDetailViewController.swift
  Danggn/Screen/Home/Controller/ListItemViewController.swift
  Danggn/Screen/Home/View/ItemDetail.storyboard
  Danggn/Screen/Home/View/PostDetailTableViewCell.xib
  Danggn/Service/FeedDetailService.swift
  Danggn/Service/FeedLikeService.swift
  Danggn/Service/FeedOnSaleService.swift
Labels: 찬미🥕, Network, Feat

#14 [Feat] PostDetail 서버 연결
  Danggn.xcodeproj/project.pbxproj
  Danggn/DataModel/BaseResponse.swift
  Danggn/DataModel/FeedDetailModel.swift
  Danggn/DataModel/FeedLikeModel.swift
  Danggn/DataModel/FeedOnSaleModel.swift
  Danggn/Screen/Home/Cell/PostDetailTableCell.swift
  Danggn/Screen/Home/Cell/PostImageCollectionCell.swift
  Danggn/Screen/Home/Cell/PostImageTableCell.swift
  Danggn/Screen/Home/Controller/ItemDetailViewController.swift
  Danggn/Screen/Home/Controller/ListItemViewController.swift
  Danggn/Screen/Home/View/ItemDetail.storyboard
  Danggn/Screen/Home/View/PostDetailTableViewCell.xib
  Danggn/Screen/Home/View/PostImageTableViewCell.xib
  Danggn/Service/FeedDetailService.swift
  Danggn/Service/FeedLikeService.swift
  Danggn/Service/FeedOnSaleService.swift
Labels: 찬미🥕, 서버

#15 [Feat] 상세 페이지 서버 연결
  Danggn.xcodeproj/project.pbxproj
  Danggn/DataModel/FeedDetailModel.swift
  Danggn/Screen/Home/Cell/PostDetailTableCell.swift
  Danggn/Screen/Home/Cell/PostDetailTableViewCell.swift
  Danggn/Screen/Home/Cell/PostImageCollectionCell.swift
  Danggn/Screen/Home/Cell/PostImageTableCell.swift
  Danggn/Screen/Home/Cell/PostImageTableViewCell.swift
  Danggn/Screen/Home/Controller/ItemDetailViewController.swift
  Danggn/Screen/Home/Controller/ListItemViewController.swift
  Danggn/Screen/Home/View/ItemDetail.storyboard
  Danggn/Screen/Home/View/PostDetailTableViewCell.xib
  Danggn/Screen/Home/View/PostImageCollectionCell.xib
  Danggn/Screen/Home/View/PostImageTableViewCell.xib
  Danggn/Service/FeedDetailService.swift
Labels: 찬미🥕, Network

#17 [Feat] 상품 등록 페이지
  Danggn.xcodeproj/project.pbxproj
  Danggn/DataModel/FeedCreateModel.swift
  Danggn/Info.plist
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_camera.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_camera.imageset/ios_camera@2x.png
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_camera.imageset/ios_camera@3x.png
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_delete1.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_delete1.imageset/ios_delete1.png
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_delete1.imageset/ios_delete1@2x.png
  Danggn/Resource/Assets.xcassets/ButtonIcons/ios_delete1.imageset/ios_delete1@3x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-1.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ios_icon_check-1.imageset/ios_icon_check.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-1.imageset/ios_icon_check@2x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-1.imageset/ios_icon_check@3x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-2.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ios_icon_check-2.imageset/ios_icon_check.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-2.imageset/ios_icon_check@2x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check-2.imageset/ios_icon_check@3x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ios_icon_check.imageset/ios_icon_check.png
  Danggn/Resource/Assets.xcassets/ios_icon_check.imageset/ios_icon_check@2x.png
  Danggn/Resource/Assets.xcassets/ios_icon_check.imageset/ios_icon_check@3x.png
  Danggn/Resource/Assets.xcassets/ios_icon_filter.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ios_icon_filter.imageset/ios_icon_filter.png
  Danggn/Resource/Assets.xcassets/ios_icon_filter.imageset/ios_icon_filter@2x.png
  Danggn/Resource/Assets.xcassets/ios_icon_filter.imageset/ios_icon_filter@3x.png
  Danggn/Resource/Assets.xcassets/ios_icon_often.imageset/Contents.json
  Danggn/Resource/Assets.xcassets/ios_icon_often.imageset/ios_icon_often.png
  Danggn/Resource/Assets.xcassets/ios_icon_often.imageset/ios_icon_often@2x.png
  Danggn/Resource/Assets.xcassets/ios_icon_often.imageset/ios_icon_often@3x.png
  Danggn/Screen/Home/Chanmi/Create/Cell/AddPhotoCollectionViewCell.swift
  Danggn/Screen/Home/Chanmi/Create/Cell/ListPhotoCollectionViewCell.swift
  Danggn/Screen/Home/Chanmi/Create/CreatePost.storyboard
  Danggn/Screen/Home/Chanmi/Create/CreatePostViewController.swift
  Danggn/Screen/Home/Chanmi/Create/Model/PhotoDataModel.swift
  Danggn/Screen/Home/Chanmi/Create/Welcome.storyboard
  Danggn/Screen/Home/Chanmi/Create/WelcomeViewController.swift
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostDetailTableViewCell.swift
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostDetailTableViewCell.xib
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostImageCollectionCell.swift
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostImageCollectionCell.xib
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostImageTableViewCell.swift
  Danggn/Screen/Home/Chanmi/Detail/Cell/PostImageTableViewCell.xib
  Danggn/Screen/Home/Chanmi/Detail/ItemDetail.storyboard
  Danggn/Screen/Home/Chanmi/Detail/ItemDetailViewController.swift
  Danggn/Screen/Home/Controller/ListItemViewController.swift
  Danggn/Service/FeedCreateService.swift
  Podfile
  Podfile.lock
Labels: 찬미🥕, Network
